### ISSUE TITLE
Create CRUD Restful API Calls

### ISSUE THREAD

**Issue by Pratik-Karnik** [DevOps-Shopcarts-S17/devops-shopcarts-s17#3]
**As a** developer
**I need** to create CRUD Restful API Calls 
**So that** we can perform various actions on our data sources.  

**Acceptance Criteria:**
```
I should be able to add, remove, view and edit products in the shopping cart
```

**Comment by WesPainter** [comment]
Should we think about breaking this issue into more manageable chunks? At least one for each of create a shopping cart, view a shopping cart, update a shopping cart, and delete a shopping cart?

**Comment by senongtor** [comment]
@WesPainter @Pratik-Karnik @trc311 I think we can basically reuse the pet flask example program and make some naming change. That can be our starting point, what do you guys think?

**Comment by Pratik-Karnik** [comment]
@senongtor Thats what I was thinking initially but when we do a GET then do we get all the shopcarts of the customers or do we get all the items in a particular shopcart. We will have to freeze on our functionality first.

**Comment by WesPainter** [comment]
Well, it is a hierarchichal structure.  At the top level, we have shopping carts.  Within them we have products, and each product has its own attributes.  So if we do GET /shopcarts, it should return a list of shopping carts.  Then if we do GET /shopcarts/id/products, it will return all products associated with the sopping cart at that ID. Getting shopcarts by user ID would be something like /shopcarts?uid=1234.

Since it is hierarchichal, I figured we could start with shopping carts and work inward.  Start simply by defining a shopping cart object, then allow GET, PUT, and DELETE.  Then we can add products, and implement updates as changes to the products in the cart.

**Comment by senongtor** [comment]
shopcarts - uid1 - product1; unitprice; quantity
                            - product2; unitprice; quantity
                 - uid2- ....
@WesPainter @Pratik-Karnik I think it'd be like that 
So when we visit /shopcarts it should return every shopchart of each customer i think
then GET should get a shopcart for a user (shopcarts/userid), POST should add a product to a cart for a specific user, and PUT will update a product for a specific user, etc.

**Comment by Pratik-Karnik** [comment]
@senongtor Wont the each User have just one shopcart though?

**Comment by Pratik-Karnik** [comment]
@WesPainter I agree with your point. Seems quite logical.

**Comment by WesPainter** [comment]
@WesPainter @Pratik-Karnik

Agreed, except I think we shouldn't necessarily restrict each uid to one shopping cart.  It's an artificial restriction, and could hinder future features (like saving a shopping cart)

So for the base url /shopcarts:

GET /shopcarts - returns all shopping carts
POST /shopcarts - creates a new empty shopcart
PUT /shopcarts - update a shopping cart (CRUD a product in that shopcart

**Comment by senongtor** [comment]
@Pratik-Karnik Yes each user will have one shopcart but I am imaging the shopcarts resource will contain all the carts for each user and we have to specify an userid to acess to his cart

**Comment by senongtor** [comment]
@WesPainter ok so PUT will handle all the update cart(update products quantity maybe), add to cart, remove from cart
